### PR TITLE
1d20 2d20 run events fix - 3

### PR DESCRIPTION
**Pull request by APeppyPlatypus**
See commit/comment in code for details. 

Changed titles to show order submitted pulls (number at end) for easier merging since worked on them in that order.

### CODE REVIEW

**Review by EvaisaDev — COMMENTED** [review]
1d20/2d20 should already be fixed.

**Comment by EvaisaDev** [comment]
Pull requests are freaking weird, half of the changes didn't actually go through it seems. maybe because I made so many changes since then myself.

**Comment by EvaisaGiac** [comment]
Mess With Wand doesn't seem to work at all, the one you didn't touch. Wonder what happened.

**Comment by EvaisaDev** [comment]
Oh by the way, when you create a pull request please remove all of the prints from your commit, or at least comment them out.
Prints are handled extremely poorly by Noita and will often cause the game to freeze if a lot are made. Especially when the logger is enabled.

**Comment by APeppyPlatypus** [comment]
> Pull requests are freaking weird, half of the changes didn't actually go through it seems. maybe because I made so many changes since then myself.

Maybe. It was showing the merge was ok before and the other branches were just ones did before but weren't messing with same sections.

**Comment by APeppyPlatypus** [comment]
> Oh by the way, when you create a pull request please remove all of the prints from your commit, or at least comment them out.
> Prints are handled extremely poorly by Noita and will often cause the game to freeze if a lot are made. Especially when the logger is enabled.

Whoops, thought did that before submitted. I'll look into removing and doing another pull.

**Comment by APeppyPlatypus** [comment]
Ah yeah this looks different now. 

Current is showing this
```
function run_events(table)
	for k, evt in pairs(table)do
		if evt.action_delayed ~= nil then
			if evt.delay_timer ~= nil then
				local p = get_players()
				
				if ( #p > 0 ) then
					for a,b in ipairs( p ) do
						add_timer_above_head( b, evt.id, evt.delay_timer, evt.timer_formatting )
					end
				end
			end
		elseif evt.action ~= nil then	
			evt.action(evt)
		end
	end
end
```


And what I had before I made update for mine was this:
```
function run_events(table)
	for k, v in pairs(table)do
		v.action(v)
	end
end
```

So can ignore this one.

**Pull request closed without merging**
